import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';
import ControlledCarousel from '@/components/slider/slider';
import SocialIcon from '@/components/common/SocialIcon';
import { Img } from '@/components/common/Img';
import Button from '@/components/common/Button';

import Link from 'next/link';
import Map from '@/components/common/Map';
import Heading from '@/components/common/Heading';
import SubHeading from '@/components/common/SubHeading';
import ImagePoint from '@/components/common/ImagePoint';
import ImageHighlight from '@/components/common/ImageHighlight';
import Product from '@/components/common/Product';
import { useEffect, useState } from 'react';

const inter = Inter({ subsets: ['latin'] });

export default function Home({ resultsOne, resultsTwo }) {
    // console.log(resultsOne);
    // console.log(resultsTwo);
    const [isVisible, setIsVisible] = useState(false);

    useEffect(() => {
        const handleScroll = () => {
            const scrollTop = window.pageYOffset;
            const windowHeight = window.innerHeight;
            const offset = 1000;

            if (scrollTop > windowHeight - offset) {
                setIsVisible(true);
            } else {
                setIsVisible(false);
            }
        };

        // Gọi hàm handleScroll khi cuộn chuột
        window.addEventListener('scroll', handleScroll);

        // Thực hiện việc cập nhật dữ liệu
        const refreshList = () => {
            // Cập nhật danh sách (nếu cần)
        };
        refreshList();

        // Xóa bỏ sự kiện cuộn chuột khi unmount component
        return () => {
            window.removeEventListener('scroll', handleScroll);
        };
    }, []);

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <div className="home__wrapper">
                    <section className=" slider__area pl-60 pr-60">
                        <div className="container-fluid">
                            <ControlledCarousel />
                        </div>
                    </section>
                    <section
                        className={`story__area pt-80 ${isVisible ? 'animate__animated animate__fadeInRight' : ''}`}
                    >
                        <div className="container d-flex flex-column align-items-center">
                            <ImageHighlight src="/assets/images/bird.png" width="300" height="160" alt="image bird" />
                            <div className="story__area__heading">
                                <Heading
                                    title="Our love story"
                                    subTitle="where it all begins"
                                    desc="Lorem ipsum dolor, sit amet consectetur adipisicing elit. Laboriosam error, enim ea minima dolore iste
                corrupti. Tenetur commodi facilis, expedita magnam officiis"
                                />
                            </div>
                            <div className="row pt-75">
                                <div className="col-lg-3 col-xl-3 col-xxl-3 col-12 col-sm-12 d-flex flex-column justify-content-center">
                                    <SubHeading
                                        title="Simona wilde"
                                        desc="Varius vel pharetra vel turpis nunc eget lorem dolor sed lorem esi deusit."
                                        className="story__heading-man"
                                    />

                                    <SocialIcon />
                                </div>
                                <div className="col-lg-6 col-xl-6 col-xxl-6 col-12 col-sm-12">
                                    <div className="story__image d-flex justify-content-center">
                                        <Image
                                            src="/assets/images/h5-img.png"
                                            alt="story wedding"
                                            objectFit="cover"
                                            width={600}
                                            height={600}
                                        />
                                    </div>
                                </div>
                                <div className="col-lg-3 col-xl-3 col-xxl-3 col-12 col-sm-12 d-flex flex-column justify-content-center">
                                    <SubHeading
                                        title="JOEL COOPER"
                                        desc="Varius vel pharetra vel turpis nunc eget lorem dolor sed lorem esi deusit."
                                        className="story__heading-girl"
                                    />
                                    <SocialIcon />
                                </div>
                            </div>
                            <div className="story__time-wrapper">
                                <div className="row">
                                    <div className="col-lg-1"></div>
                                    <div className="col-12 col-sm-6 col-lg-2 d-sm-flex justify-content-center">
                                        <div className="box story-week box">
                                            <h4>24</h4>
                                            <span>Weeks</span>
                                        </div>
                                    </div>

                                    <div className="col-12 col-sm-6 col-lg-2 d-sm-flex justify-content-center">
                                        <div className="story-day box">
                                            <h4>04</h4>
                                            <span>Days</span>
                                        </div>
                                    </div>

                                    <div className="col-12 col-sm-6 col-lg-2 d-sm-flex justify-content-center">
                                        <div className="story-hour box">
                                            <h4>21</h4>
                                            <span>Weeks</span>
                                        </div>
                                    </div>

                                    <div className="col-12 col-sm-6 col-lg-2 d-sm-flex justify-content-center">
                                        <div className="story-minute box">
                                            <h4>59</h4>
                                            <span>Minutes</span>
                                        </div>
                                    </div>

                                    <div className="col-12 col-sm-6 col-lg-2 d-sm-flex justify-content-center">
                                        <div className="story-second box">
                                            <h4>24</h4>
                                            <span>Second</span>
                                        </div>
                                    </div>
                                    <div className="col-lg-1"></div>
                                </div>
                            </div>
                        </div>
                        <div className="container-fluid pt-80">
                            <ImagePoint
                                title="SAVE THE DATE"
                                subTitle="WE WOULD LIKE TO INVITE YOU TO CELEBRATE WITH US"
                                src="/assets/images/h5-parallax-01.jpg"
                                width="1800"
                                height="750"
                            />
                        </div>
                    </section>
                    <section
                        className={`gallery__area pt-80 ${isVisible ? 'animate__animated animate__fadeInRight' : ''}`}
                    >
                        <div className="container text-center align-items-center d-flex flex-column">
                            <ImageHighlight src="/assets/images/bird.png" width="300" height="160" alt="image bird" />

                            <div className="gallery__area__heading">
                                <h3 className="section__title">OUR LOVE GALLERY</h3>
                                <h4 className="section__sub__title">MAGIC CAPTURED</h4>
                                <p className="section__des">
                                    Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor
                                    incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud
                                    exercitation
                                </p>
                            </div>
                            <div className="row gallery__image-wrapper pt-60">
                                <div className="col-lg-6 col-sm-12 col-12">
                                    <div className="gallery__image">
                                        <Image
                                            src="/assets/images/h5-img-2.jpg"
                                            alt="gallery__image"
                                            width={740}
                                            height={740}
                                            objectFit="cover"
                                        />
                                    </div>
                                </div>
                                <div className="col-lg-3 col-sm-6 col-12 d-flex flex-column align-item-center justify-content-between">
                                    <div className="gallery__image">
                                        <Image
                                            src="/assets/images/h5-img-3.jpg"
                                            alt="gallery__image"
                                            width={310}
                                            height={310}
                                            objectFit="cover"
                                        />
                                    </div>
                                    <div className="gallery__image">
                                        <Image
                                            src="/assets/images/h5-img-4.jpg"
                                            alt="gallery__image gallery__image"
                                            width={310}
                                            height={310}
                                            objectFit="cover"
                                            className=""
                                        />
                                    </div>
                                </div>
                                <div className="col-lg-3 col-sm-6 col-12">
                                    <div className="gallery__image">
                                        <Image
                                            src="/assets/images/h5-img-05.jpg"
                                            alt="gallery__image"
                                            width={640}
                                            height={640}
                                            objectFit="cover"
                                        />
                                    </div>
                                </div>
                            </div>
                        </div>
                    </section>
                    <section className="scroll__area pt-80">
                        <div className="container-fluid d-flex scroll-group">
                            <div className="scroll-text">
                                <i className="fa-solid fa-diamond"></i>
                                ENDLESS INSPIRATIONS
                            </div>
                            <div className="scroll-text">
                                <i className="fa-solid fa-diamond"></i>
                                AGNIFICENT WEDDING
                            </div>
                            <div className="scroll-text">
                                <i className="fa-solid fa-diamond"></i>
                                BEAUTIFUL IDEAS
                            </div>
                            <div className="scroll-text">
                                <i className="fa-solid fa-diamond"></i>
                                ENDLESS INSPIRATIONS{' '}
                            </div>
                            <div className="scroll-text">
                                <i className="fa-solid fa-diamond"></i>
                                AGNIFICENT WEDDING
                            </div>
                            <div className="scroll-text">
                                <i className="fa-solid fa-diamond"></i>
                                BEAUTIFUL IDEAS
                            </div>
                        </div>
                    </section>
                    <section className="timeline__area pt-80">
                        <div className="container">
                            <div className="timeline__area__heading">
                                <Heading title="LOVE STORY TIMELINE" subTitle="TAKE A LOOK AT OUR STORY" />
                            </div>
                            <div className="timeline__process">
                                <div className="row align-items-center">
                                    <span className="timeline__process-wire"></span>
                                    <div className="col-12 col-sm-6 col-lg-3">
                                        <div className="timeline__image d-flex  justify-content-center">
                                            <Image
                                                src="/assets/images/h5-decor-01.png"
                                                alt="timeline image"
                                                width={200}
                                                height={200}
                                                objectFit="cover"
                                            />
                                        </div>
                                        <div className="process-wrapper text-center ">
                                            <h3 className="section__title-4">FIRST MEETING</h3>
                                            <h5 className="section__sub-title-4">A FRIEND&apos;S PARTY</h5>
                                            <p className="section__des-4 mt-3">
                                                Duis aute irure dolor in reprehenderit in voluptate velit esse cillum
                                            </p>
                                        </div>
                                    </div>
                                    <div className="col-12 col-sm-6 col-lg-3">
                                        <div className="timeline__image">
                                            <Image
                                                src="/assets/images/h5-decor-02.png"
                                                alt="timeline image"
                                                width={200}
                                                height={200}
                                                objectFit="cover"
                                            />
                                        </div>

                                        <div className="process-wrapper">
                                            <h3 className="section__title-4">FIRST MEETING</h3>
                                            <h5 className="section__sub-title-4">A FRIEND&apos;S PARTY</h5>
                                            <p className="section__des-4 mt-3">
                                                Duis aute irure dolor in reprehenderit in voluptate velit esse cillum
                                            </p>
                                        </div>
                                    </div>
                                    <div className="col-12 col-sm-6 col-lg-3">
                                        <div className="timeline__image">
                                            <Image
                                                src="/assets/images/h5-decor-03.png"
                                                alt="timeline image"
                                                width={200}
                                                height={200}
                                                objectFit="cover"
                                            />
                                        </div>

                                        <div className="process-wrapper">
                                            <h3 className="section__title-4">FIRST MEETING</h3>
                                            <h5 className="section__sub-title-4">A FRIEND&apos;S PARTY</h5>
                                            <p className="section__des-4 mt-3">
                                                Duis aute irure dolor in reprehenderit in voluptate velit esse cillum
                                            </p>
                                        </div>
                                    </div>
                                    <div className="col-12 col-sm-6 col-lg-3">
                                        <div className="timeline__image">
                                            <Image
                                                src="/assets/images/h5-decor-04.png"
                                                alt="timeline image"
                                                width={200}
                                                height={200}
                                                objectFit="cover"
                                            />
                                        </div>

                                        <div className="process-wrapper">
                                            <h3 className="section__title-4">FIRST MEETING</h3>
                                            <h5 className="section__sub-title-4">A FRIEND&apos;S PARTY</h5>
                                            <p className="section__des-4 mt-3">
                                                Duis aute irure dolor in reprehenderit in voluptate velit esse cillum
                                            </p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div className="container-fluid pt-80">
                            <ImagePoint
                                title="SIMONA & NOEL"
                                subTitle="LET US KNOW IF YOU ARE COMING TO CELEBRATE OUR LOVE"
                                src="/assets/images/h5-parallax-02.jpg"
                                alt="SIMONA wedding"
                                width="1800"
                                height="750"
                            />
                        </div>
                    </section>
                    <section className="brides__area pt-80">
                        <div className="container">
                            <Heading
                                title="BRIDESMAIDES & GROOMSMEN"
                                subTitle="MAGIC CAPTURE"
                                desc="Lorem ipsum dolor, sit amet consectetur adipisicing elit. Laboriosam error, enim ea minima dolore iste
                corrupti. Tenetur commodi facilis, expedita magnam officiis asperiores unde recusandae accusamus enim
                modi, adipisci ea."
                            />
                            <div className="pt-60 brides__grooms-wrapper">
                                <div className="row ">
                                    <div className="col-12 col-sm-4 col-lg-4">
                                        <div className="brides__grooms-image">
                                            <Image
                                                src="/assets/images/team-img-2.png"
                                                alt="brides grooms image"
                                                width={300}
                                                height={300}
                                            />
                                            <div className="brides__grooms-effect">
                                                <Image
                                                    src="/assets/images/team-decor-img.png"
                                                    alt="brides grooms image"
                                                    width={400}
                                                    height={400}
                                                />
                                            </div>
                                        </div>
                                        <h4 className="section__title-4">ANNA STILL</h4>
                                        <h5 className="section__sub-title-4">BRIEDMAID</h5>
                                        <div>
                                            <div className="brides__grooms-image">
                                                <Image
                                                    src="/assets/images/team-img-4.png"
                                                    alt="brides grooms image"
                                                    width={300}
                                                    height={300}
                                                />
                                                <div className="brides__grooms-effect">
                                                    <img
                                                        src="/assets/images/team-decor-img.png"
                                                        alt="brides grooms image"
                                                    />
                                                </div>
                                            </div>
                                            <h4 className="section__title-4">LAURA MITTE</h4>
                                            <h5 className="section__sub-title-4">BRIEDMAID</h5>
                                        </div>
                                    </div>
                                    <div className="col-12 col-sm-4 col-lg-4">
                                        <div>
                                            <div className="brides__grooms-image">
                                                <Image
                                                    src="/assets/images/team-img-7.png"
                                                    alt="brides grooms image"
                                                    width={300}
                                                    height={300}
                                                />
                                                <div className="brides__grooms-effect">
                                                    <img
                                                        src="/assets/images/team-decor-img.png"
                                                        alt="brides grooms image"
                                                    />
                                                </div>
                                            </div>

                                            <h4 className="section__title-4">SIMONA JAGGER</h4>
                                            <h5 className="section__sub-title-4">BRIEDMAID</h5>
                                        </div>
                                        <div>
                                            <div className="brides__grooms-image">
                                                <Image
                                                    src="/assets/images/team-img-4.png"
                                                    alt="brides grooms image"
                                                    width={300}
                                                    height={300}
                                                />
                                                <div className="brides__grooms-effect">
                                                    <img
                                                        src="/assets/images/team-decor-img.png"
                                                        alt="brides grooms image"
                                                    />
                                                </div>
                                            </div>

                                            <h4 className="section__title-4">SIMONA JAGGER</h4>
                                            <h5 className="section__sub-title-4">BRIEDMAID</h5>
                                        </div>
                                    </div>
                                    <div className="col-12 col-sm-4 col-lg-4">
                                        <div>
                                            <div className="brides__grooms-image">
                                                <Image
                                                    src="/assets/images/team-img-3.png"
                                                    alt="brides grooms image"
                                                    width={300}
                                                    height={300}
                                                />
                                                <div className="brides__grooms-effect">
                                                    <img
                                                        src="/assets/images/team-decor-img.png"
                                                        alt="brides grooms image"
                                                    />
                                                </div>
                                            </div>
                                            <h4 className="section__title-4">SIMONA JAGGER</h4>
                                            <h5 className="section__sub-title-4">BRIEDMAID</h5>
                                        </div>
                                        <div>
                                            <div className="brides__grooms-image">
                                                <Image
                                                    src="/assets/images/team-img-6.png"
                                                    alt="brides grooms image"
                                                    width={300}
                                                    height={300}
                                                />
                                                <div className="brides__grooms-effect">
                                                    <img
                                                        src="/assets/images/team-decor-img.png"
                                                        alt="brides grooms image"
                                                    />
                                                </div>
                                            </div>
                                            <h4 className="section__title-4">SIMONA JAGGER</h4>
                                            <h5 className="section__sub-title-4">BRIEDMAID</h5>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div className="container-fluid pt-80">
                            <ImagePoint
                                title="WE CAN'T WAIT TO SEE"
                                subTitle="SUNADAY 17, JANUART 2023 AT 17:00"
                                src="/assets/images/h5-parallax-03.jpg"
                                alt="SIMONA wedding"
                                width="1800"
                                height="750"
                            />
                        </div>
                        <div className="container pt-80">
                            <div className="row">
                                <div className="col-12 col-sm-3 col-lg-2">
                                    <div className="box introduce-image">
                                        <Image
                                            src="/assets/images/hover-client-new.png"
                                            alt="introduce image"
                                            width={170}
                                            height={170}
                                            objectFit="cover"
                                        />
                                    </div>
                                </div>
                                <div className="col-12 col-sm-3 col-lg-2">
                                    <div className="box introduce-image">
                                        <Image
                                            src="/assets/images/h3-client-2.png"
                                            alt="introduce image"
                                            width={170}
                                            height={170}
                                            objectFit="cover"
                                        />
                                    </div>
                                </div>
                                <div className="col-12 col-sm-3 col-lg-2">
                                    <div className="box introduce-image">
                                        <Image
                                            src="/assets/images/h3-client-hover-3.png"
                                            alt="introduce image"
                                            width={170}
                                            height={170}
                                            objectFit="cover"
                                        />
                                    </div>
                                </div>
                                <div className="col-12 col-sm-3 col-lg-2">
                                    <div className="box introduce-image">
                                        <Image
                                            src="/assets/images/h3-client-hover-04.png"
                                            alt="introduce image"
                                            width={170}
                                            height={170}
                                            objectFit="cover"
                                        />
                                    </div>
                                </div>
                                <div className="col-12 col-sm-3 col-lg-2">
                                    <div className="box introduce-image">
                                        <Image
                                            src="/assets/images/h3-client-hover-05.png"
                                            alt="introduce image"
                                            width={170}
                                            height={170}
                                            objectFit="cover"
                                        />
                                    </div>
                                </div>
                                <div className="col-12 col-sm-3 col-lg-2">
                                    <div className="box introduce-image">
                                        <Image
                                            src="/assets/images/h3-client-hover-6.png"
                                            alt="introduce image"
                                            width={170}
                                            height={170}
                                            objectFit="cover"
                                        />
                                    </div>
                                </div>
                            </div>
                        </div>
                    </section>
                    <section className="partners__area pt-80">
                        <div className="container">
                            <div className="partners__area__heading">
                                <Heading
                                    title="OUR PARTNERS"
                                    subTitle="WEDDING ORGANIZATION"
                                    desc="Lorem ipsum dolor, sit amet consectetur adipisicing elit. Laboriosam error, enim ea minima dolore iste
                corrupti. Tenetur commodi facilis, expedita magnam officiis asperiores unde recusandae accusamus enim
                modi, adipisci ea."
                                />
                            </div>
                            <div className="partners__product">
                                <Product />
                            </div>
                        </div>
                        <div className="map__area">
                            <Map />
                        </div>
                    </section>
                </div>
            </main>
        </>
    );
}

export async function getServerSideProps() {
    const resultsOne = await fetch('https://saurav.tech/NewsAPI/top-headlines/category/health/in.json').then((res) =>
        res.json(),
    );

    //Who to follow section
    const resultsTwo = await fetch('https://randomuser.me/api/?results=30&inc=name,login,picture').then((res) =>
        res.json(),
    );

    return {
        props: {
            resultsOne,
            resultsTwo,
        },
    };
}
